### ISSUE TITLE
why does this not work? (understanding se.fit = T)

### ISSUE THREAD

**Issue by anniejw6** [anniejw6/modmarg#1]
Otherwise re-write delta method vignette.

```
set.seed(12345)

n = 1000
df <- data.frame(
  x1 = sample(0:1, n, replace = T),
  x2 = runif(n),
  e = runif(n)
)

df$y <- 3 * df$x1 + 4 * df$x2 + df$e
df$x1 <- factor(df$x1)

z <- aiEstimation::ai_toplines(
  outcome = 'y',
  treat = 'x1',
  covar = 'x2',
  model =  'reg',
  df = df
)


mod <- glm(y ~ x1 + x2, data = df, family = 'gaussian')

newd <- df
newd$x1[newd$x1 == 0] <- 1

q <- predict(mod, newdata = newd, se.fit = T)

z$model
summary(mod)

z$margins
mean(q$fit)

z$margins
sqrt(sum(q$se.fit^2)/length(q$se.fit))
```

**Comment by nathanielolin** [comment]
The short answer is that the estimate of the average predicted value is a function of a random variable, and has its own variance. The sample variance of the predicted values for the observations in our sample is not the same thing as the theoretical variance of the average predicted value.

We want an estimate of `mean(y)` when `x1 = 1`, and we've chosen `mean(q)` as our estimator (where `q` is the vector of predicted probabilities for our data when letting `x1 = 1`). We know from the delta method that, if `mean(y)` follows the central limit theorem (and it does), then `g(y)` has variance `g'(y) * vcov(mod) * t(g'(y))` (see page 19 [here](http://www.phidot.org/software/mark/docs/book/pdf/app_2.pdf) although [Wikipedia](https://en.wikipedia.org/wiki/Delta_method) is more concise.

The nice thing about an OLS example is that you can just cheat and look at the standard error you get from 
```
predict(mod, newdata = data.frame(x1 = mean(df$x1), x2 = mean(df$x2)), se.fit = T)
```
because everything is additively separable and you can extrapolate straight to the mean predicted value by just taking the mean of all the covariates.

**Comment by anniejw6** [comment]
I think my goal here was not so much for you to post an answer here (though I do appreciate you explaining this for the umpteenth time) but to put it in a vignette because I think it's a pretty reasonable question to ask.

**Comment by nathanielolin** [comment]
Agree with the latter, and, will do re: the former.
